version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: quizen
      DB_SSL_MODE: disable
    ports:
      - "8080:8080"
    tty: true # コンテナの起動永続化
  db:
    image: postgres:10.13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quizen
    ports:
      - 5432:5432
    volumes:
      - "./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
